/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./src/components/project/ActionBar.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    BuildDialog: typeof import('./src/components/project/BuildDialog.vue')['default']
    MetricsBar: typeof import('./src/components/project/MetricsBar.vue')['default']
    PlaceholderPage: typeof import('./src/components/PlaceholderPage.vue')['default']
    ProjectCard: typeof import('./src/components/project/ProjectCard.vue')['default']
    ProjectFormDialog: typeof import('./src/components/project/ProjectFormDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBadge: typeof import('./src/components/project/StatusBadge.vue')['default']
    StatusBar: typeof import('./src/components/layout/StatusBar.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
  }
}
